# Generated by Django 5.2.3 on 2025-06-28 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainer',
            options={'ordering': ('user_profile__first_name', 'user_profile__last_name'), 'verbose_name': 'Trainer', 'verbose_name_plural': 'Trainers'},
        ),
        migrations.AlterModelOptions(
            name='trainerpokemon',
            options={'ordering': ('trainer__user_profile__first_name', 'trainer__user_profile__last_name', 'pokemon__pokemon_id'), 'verbose_name': 'Trainer Pokémon', 'verbose_name_plural': 'Trainer Pokémons'},
        ),
    ]
