# Generated by Django 5.2.3 on 2025-06-28 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pokemon_options_alter_pokemontype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon',
            options={'ordering': ('pokemon_id',), 'verbose_name': 'Pokémon', 'verbose_name_plural': 'Pokémon'},
        ),
        migrations.AlterModelOptions(
            name='pokemontype',
            options={'ordering': ('name',), 'verbose_name': 'Pokémon Type', 'verbose_name_plural': 'Pokémon Type'},
        ),
    ]
