# Generated by Django 5.2.3 on 2025-06-28 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_userprofile_options_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ('first_name', 'last_name'), 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profile'},
        ),
    ]
